"""Added Rack.

Revision ID: 05ee3aa09c03
Revises: 35e3c027e5a2
Create Date: 2023-11-17 14:36:43.274106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ee3aa09c03'
down_revision: Union[str, None] = '35e3c027e5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racks',
                    sa.Column('rack_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('warehouse_id', sa.Integer(), nullable=False),
                    sa.Column('rack_position', sa.String(length=10), nullable=False),
                    sa.Column('overall_capacity', sa.Numeric(precision=20, scale=2, asdecimal=False), nullable=False),
                    sa.Column('remaining_capacity', sa.Numeric(precision=20, scale=2, asdecimal=False), nullable=False),
                    sa.CheckConstraint('overall_capacity > 0', name='check_overall_capacity'),
                    sa.CheckConstraint('remaining_capacity <= overall_capacity', name='check_remaining_capacity'),
                    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
                    sa.PrimaryKeyConstraint('rack_id')
                    )
    op.create_index(op.f('ix_racks_rack_id'), 'racks', ['rack_id'], unique=False)
    op.create_index(op.f('ix_racks_rack_position'), 'racks', ['rack_position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_racks_rack_position'), table_name='racks')
    op.drop_index(op.f('ix_racks_rack_id'), table_name='racks')
    op.drop_table('racks')
    # ### end Alembic commands ###
