"""created order model

Revision ID: 211f699801bf
Revises: bd60ffbb9e34
Create Date: 2023-10-22 14:55:10.678637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211f699801bf'
down_revision: Union[str, None] = 'bd60ffbb9e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('recipient_store_id', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('order_status', sa.Enum('new', 'processing', 'submitted', 'finished', 'cancelled', name='order_status'), nullable=False),
    sa.CheckConstraint('total_price > 0', name='check_total_price'),
    sa.ForeignKeyConstraint(['recipient_store_id'], ['stores.store_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
