"""Added Transaction.

Revision ID: 255683876ff8
Revises: e1fb75b312cf
Create Date: 2023-11-17 14:39:13.791510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255683876ff8'
down_revision: Union[str, None] = 'e1fb75b312cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
                    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('supplier_id', sa.Integer(), nullable=True),
                    sa.Column('recipient_id', sa.Integer(), nullable=True),
                    sa.Column('shipper_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('new', 'processing', 'submitted', 'finished', 'cancelled', 'delivered',
                                                name='transaction_status'), nullable=False),
                    sa.Column('total_price', sa.Numeric(precision=20, scale=2, asdecimal=False), nullable=False),
                    sa.Column('is_internal', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.CheckConstraint('recipient_id <> supplier_id', name='check_recipient_supplier'),
                    sa.ForeignKeyConstraint(['recipient_id'], ['warehouses.warehouse_id'], ),
                    sa.ForeignKeyConstraint(['shipper_id'], ['users.user_id'], ),
                    sa.ForeignKeyConstraint(['supplier_id'], ['warehouses.warehouse_id'], ),
                    sa.PrimaryKeyConstraint('transaction_id')
                    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
