"""Added Warehouse

Revision ID: 282f6578e187
Revises: 7b30102a9884
Create Date: 2023-11-17 14:35:30.570272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282f6578e187'
down_revision: Union[str, None] = '7b30102a9884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
                    sa.Column('warehouse_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('company_id', sa.Integer(), nullable=False),
                    sa.Column('supervisor_id', sa.Integer(), nullable=False),
                    sa.Column('warehouse_name', sa.String(length=50), nullable=False),
                    sa.Column('warehouse_address', sa.String(length=255), nullable=False),
                    sa.Column('overall_capacity', sa.Numeric(precision=20, scale=2, asdecimal=False), nullable=False),
                    sa.Column('remaining_capacity', sa.Numeric(precision=20, scale=2, asdecimal=False), nullable=False),
                    sa.Column('warehouse_type',
                              sa.Enum('freezer', 'refrigerated', 'dry', 'hazardous', name='warehouse_type'),
                              nullable=False),
                    sa.CheckConstraint('overall_capacity > 0', name='check_overall_capacity'),
                    sa.CheckConstraint('remaining_capacity <= overall_capacity', name='check_remaining_capacity'),
                    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
                    sa.ForeignKeyConstraint(['supervisor_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('warehouse_id')
                    )
    op.create_index(op.f('ix_warehouses_warehouse_address'), 'warehouses', ['warehouse_address'], unique=False)
    op.create_index(op.f('ix_warehouses_warehouse_id'), 'warehouses', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_warehouses_warehouse_name'), 'warehouses', ['warehouse_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouses_warehouse_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_warehouse_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_warehouse_address'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
