"""Added Order.

Revision ID: 35e3c027e5a2
Revises: 282f6578e187
Create Date: 2023-11-17 14:35:56.403630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e3c027e5a2'
down_revision: Union[str, None] = '282f6578e187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
                    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('supplier_id', sa.Integer(), nullable=False),
                    sa.Column('recipient_vendor_id', sa.Integer(), nullable=True),
                    sa.Column('total_price', sa.Numeric(precision=20, scale=2, asdecimal=False), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('order_status',
                              sa.Enum('new', 'processing', 'submitted', 'finished', 'cancelled', 'delivered', 'lost',
                                      'damaged', name='order_status'), nullable=False),
                    sa.CheckConstraint('total_price > 0', name='check_total_price'),
                    sa.ForeignKeyConstraint(['recipient_vendor_id'], ['vendors.vendor_id'], ),
                    sa.ForeignKeyConstraint(['supplier_id'], ['warehouses.warehouse_id'], ),
                    sa.PrimaryKeyConstraint('order_id')
                    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
