"""created rack model

Revision ID: 3ba5befaaa16
Revises: 211f699801bf
Create Date: 2023-10-22 15:24:55.142662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba5befaaa16'
down_revision: Union[str, None] = '211f699801bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racks',
    sa.Column('rack_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('rack_position', sa.String(length=10), nullable=True),
    sa.Column('overall_capacity', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('remaining_capacity', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.CheckConstraint('overall_capacity > 0', name='check_overall_capacity'),
    sa.CheckConstraint('remaining_capacity <= overall_capacity', name='check_remaining_capacity'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('rack_id')
    )
    op.create_index(op.f('ix_racks_rack_id'), 'racks', ['rack_id'], unique=False)
    op.create_index(op.f('ix_racks_rack_position'), 'racks', ['rack_position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_racks_rack_position'), table_name='racks')
    op.drop_index(op.f('ix_racks_rack_id'), table_name='racks')
    op.drop_table('racks')
    # ### end Alembic commands ###
