"""created store model

Revision ID: 3f5ee88c5c0a
Revises: 12e7da2aa784
Create Date: 2023-10-22 13:53:44.009818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5ee88c5c0a'
down_revision: Union[str, None] = '12e7da2aa784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('store_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('store_owner_id', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(length=50), nullable=True),
    sa.Column('store_address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['store_owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index(op.f('ix_stores_store_address'), 'stores', ['store_address'], unique=False)
    op.create_index(op.f('ix_stores_store_id'), 'stores', ['store_id'], unique=False)
    op.create_index(op.f('ix_stores_store_name'), 'stores', ['store_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_store_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_store_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_store_address'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
