"""Added shipper to product and transaction.

Revision ID: 47c4ec779a3d
Revises: c784c5131f02
Create Date: 2023-11-11 02:26:50.326665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c4ec779a3d'
down_revision: Union[str, None] = 'c784c5131f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('total_volume', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('orders', sa.Column('shipper_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['shipper_id'], ['user_id'])
    op.add_column('products', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['company_id'])
    op.add_column('transactions', sa.Column('shipper_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('total_price', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('transactions', sa.Column('is_internal', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['shipper_id'], ['user_id'])
    op.create_index(op.f('ix_users_user_surname'), 'users', ['user_surname'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_surname'), table_name='users')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'is_internal')
    op.drop_column('transactions', 'total_price')
    op.drop_column('transactions', 'shipper_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'company_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'shipper_id')
    op.drop_column('inventories', 'total_volume')
    # ### end Alembic commands ###
