"""Add transaction model

Revision ID: 7db9a14f29b4
Revises: 0c2c7b34f20b
Create Date: 2023-10-23 21:51:55.267591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db9a14f29b4'
down_revision: Union[str, None] = '0c2c7b34f20b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('new', 'processing', 'submitted', 'finished', 'cancelled', name='transaction_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('recipient_id <> supplier_id', name='check_recipient_supplier'),
    sa.ForeignKeyConstraint(['recipient_id'], ['warehouses.warehouse_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
