"""added_thrown_items

Revision ID: 8d98673fa6f3
Revises: cf03e536d62a
Create Date: 2023-12-19 15:27:20.928897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d98673fa6f3'
down_revision: Union[str, None] = 'cf03e536d62a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thrown_items',
    sa.Column('thrown_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('thrown_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_quantity'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.warehouse_id'], ),
    sa.PrimaryKeyConstraint('thrown_item_id'),
    sa.UniqueConstraint('warehouse_id', 'product_id', 'thrown_at')
    )
    op.create_index(op.f('ix_thrown_items_thrown_item_id'), 'thrown_items', ['thrown_item_id'], unique=False)
    op.add_column('users', sa.Column('is_password_forgotten', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_password_forgotten')
    op.drop_index(op.f('ix_thrown_items_thrown_item_id'), table_name='thrown_items')
    op.drop_table('thrown_items')
    # ### end Alembic commands ###
