"""add roles to user

Revision ID: a63434d31726
Revises: 3f5ee88c5c0a
Create Date: 2023-10-22 14:08:44.534013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63434d31726'
down_revision: Union[str, None] = '3f5ee88c5c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE user_role AS ENUM ('owner', 'manager', 'shipper', 'customer');")
    op.add_column('users', sa.Column('user_role', sa.Enum('owner', 'manager', 'shipper', 'customer', name='user_role'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_role')
    op.execute("DROP TYPE user_role;")
    # ### end Alembic commands ###
