"""add default admin and company


Revision ID: cf03e536d62a
Revises: d73ead2bb5f2
Create Date: 2023-12-02 21:21:23.093972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from db_config import get_session
from models import User, Company
from utilities import hash_password

# revision identifiers, used by Alembic.
revision: str = 'cf03e536d62a'
down_revision: Union[str, None] = 'd73ead2bb5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with get_session() as session:
        import os
        from dotenv import load_dotenv
        load_dotenv()
        admin_password = os.getenv("ADMIN_PASSWORD")

        company = Company(
            company_name="Administrating Company",
            company_email="administration_wms@gmail.com"
        )
        session.add(company)
        session.flush()

        admin = User(
            company_id=company.company_id,
            user_name="System Administrator",
            user_surname="sys_admin",
            user_phone="+998992281448",
            user_email="sys_admin_wms@gmail.com",
            user_address="WMS Administration company street.",
            user_password=hash_password(admin_password).decode("utf8"),
            user_role="admin"
        )
        session.add(admin)
        session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
