"""added_lost_items

Revision ID: d73ead2bb5f2
Revises: f1f5b6c78110
Create Date: 2023-12-02 15:59:36.107274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73ead2bb5f2'
down_revision: Union[str, None] = 'f1f5b6c78110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lost_items',
                    sa.Column('lost_item_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.CheckConstraint('quantity > 0', name='check_quantity'),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
                    sa.PrimaryKeyConstraint('lost_item_id'),
                    sa.UniqueConstraint('order_id', 'product_id')
                    )
    op.create_index(op.f('ix_lost_items_lost_item_id'), 'lost_items', ['lost_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lost_items_lost_item_id'), table_name='lost_items')
    op.drop_table('lost_items')
    # ### end Alembic commands ###
