"""Added Transaction Item.

Revision ID: d97949d7a798
Revises: f3c683bc6efc
Create Date: 2023-11-17 14:39:39.678922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd97949d7a798'
down_revision: Union[str, None] = 'f3c683bc6efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_items',
                    sa.Column('transaction_item_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('transaction_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.CheckConstraint('quantity > 0', name='check_quantity'),
                    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
                    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
                    sa.PrimaryKeyConstraint('transaction_item_id'),
                    sa.UniqueConstraint('product_id', 'transaction_id')
                    )
    op.create_index(op.f('ix_transaction_items_transaction_item_id'), 'transaction_items', ['transaction_item_id'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_items_transaction_item_id'), table_name='transaction_items')
    op.drop_table('transaction_items')
    # ### end Alembic commands ###
