"""Added Inventory

Revision ID: e1fb75b312cf
Revises: 25a2c11d705b
Create Date: 2023-11-17 14:38:23.431201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fb75b312cf'
down_revision: Union[str, None] = '25a2c11d705b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
                    sa.Column('inventory_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('rack_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('total_volume', sa.Numeric(precision=20, scale=2, asdecimal=False), nullable=False),
                    sa.Column('arrival_date', sa.Date(), nullable=False),
                    sa.Column('expiry_date', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
                    sa.ForeignKeyConstraint(['rack_id'], ['racks.rack_id'], ),
                    sa.PrimaryKeyConstraint('inventory_id'),
                    sa.UniqueConstraint('rack_id', 'product_id')
                    )
    op.create_index(op.f('ix_inventories_inventory_id'), 'inventories', ['inventory_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventories_inventory_id'), table_name='inventories')
    op.drop_table('inventories')
    # ### end Alembic commands ###
