"""invetory-fix

Revision ID: e9e179190779
Revises: 8d98673fa6f3
Create Date: 2023-12-19 17:13:17.603162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e179190779'
down_revision: Union[str, None] = '8d98673fa6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventories', 'companies', ['company_id'], ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.drop_column('inventories', 'company_id')
    # ### end Alembic commands ###
