"""Add order_item model

Revision ID: e9ebebc1351f
Revises: 2cd561b8a7f9
Create Date: 2023-10-23 21:13:35.691255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ebebc1351f'
down_revision: Union[str, None] = '2cd561b8a7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('expiry_duration', sa.Integer(), nullable=True),
    sa.CheckConstraint('price > 0', name='check_price'),
    sa.CheckConstraint('volume > 0', name='check_volume'),
    sa.CheckConstraint('weight > 0', name='check_weight'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_products_description'), 'products', ['description'], unique=False)
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_table('order_items',
    sa.Column('order_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.CheckConstraint('quantity > 0', name='check_quantity'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('order_item_id'),
    sa.UniqueConstraint('order_id', 'product_id')
    )
    op.create_index(op.f('ix_order_items_order_item_id'), 'order_items', ['order_item_id'], unique=False)
    op.drop_index('ix_product_description', table_name='product')
    op.drop_index('ix_product_product_id', table_name='product')
    op.drop_index('ix_product_product_name', table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('weight', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('volume', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('expiry_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('price > 0::numeric', name='check_price'),
    sa.CheckConstraint('volume > 0::numeric', name='check_volume'),
    sa.CheckConstraint('weight > 0::numeric', name='check_weight'),
    sa.PrimaryKeyConstraint('product_id', name='product_pkey')
    )
    op.create_index('ix_product_product_name', 'product', ['product_name'], unique=False)
    op.create_index('ix_product_product_id', 'product', ['product_id'], unique=False)
    op.create_index('ix_product_description', 'product', ['description'], unique=False)
    op.drop_index(op.f('ix_order_items_order_item_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_description'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
