"""Added transport relationships

Revision ID: f1f5b6c78110
Revises: 18d05b0d34aa
Create Date: 2023-11-24 16:18:48.778604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f5b6c78110'
down_revision: Union[str, None] = '18d05b0d34aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('transport_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'transports', ['transport_id'], ['transport_id'])
    op.add_column('transactions', sa.Column('transport_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'transports', ['transport_id'], ['transport_id'])
    op.add_column('warehouses', sa.Column('supervisor_id', sa.Integer(), nullable=False))
    op.drop_constraint('warehouses_manager_id_fkey', 'warehouses', type_='foreignkey')
    op.create_foreign_key(None, 'warehouses', 'users', ['supervisor_id'], ['user_id'])
    op.drop_column('warehouses', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'warehouses', type_='foreignkey')
    op.create_foreign_key('warehouses_manager_id_fkey', 'warehouses', 'users', ['manager_id'], ['user_id'])
    op.drop_column('warehouses', 'supervisor_id')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'transport_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'transport_id')
    # ### end Alembic commands ###
