"""Added Order Item.

Revision ID: f3c683bc6efc
Revises: 255683876ff8
Create Date: 2023-11-17 14:39:27.337933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c683bc6efc'
down_revision: Union[str, None] = '255683876ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
                    sa.Column('order_item_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.CheckConstraint('quantity > 0', name='check_quantity'),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
                    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
                    sa.PrimaryKeyConstraint('order_item_id'),
                    sa.UniqueConstraint('order_id', 'product_id')
                    )
    op.create_index(op.f('ix_order_items_order_item_id'), 'order_items', ['order_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_item_id'), table_name='order_items')
    op.drop_table('order_items')
    # ### end Alembic commands ###
